### ISSUE TITLE
[DMP 2024]: Unified `policyengine` Python package

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine.py#1]
Description
-----------

We are looking to develop a Python package called `policyengine` that will serve as a unified interface for our country-specific policy simulation packages (e.g., `policyengine_us`, `policyengine_uk`). This package will provide a consistent API for users to perform policy simulations, conduct analyses, and generate visualizations across different countries. The package will include two main simulation classes: `Microsimulation` for running simulations on microdata and `IndividualSim` for calculating outcomes for a single household. Additionally, the package will offer analytics and charting functionality to facilitate cross-country comparisons and visualizations. A key feature of the package will be the ability to reproduce charts and visualizations from the PolicyEngine web interface, enabling users to generate insightful visual representations of simulation results programmatically.

Goals
-----

*   Design a modular and extensible architecture for the `policyengine` package.
    
*   Implement the `Microsimulation` and `IndividualSim` classes for policy simulations.
    
*   Develop analytics and charting modules for cross-country analyses and visualizations.
    
*   Enable users to reproduce charts from the PolicyEngine web interface, including:
    *   Budgetary breakdowns
    *   Charts by income decile
    *   Poverty breakdowns by demographic groups
    *   Income inequality impacts for microsimulations
    *   Net income, marginal tax rates, and other variables with respect to earnings for individual households (under baseline and reform law)
    *   Evolution of policy parameters' values
*   Utilize Plotly for interactive and visually appealing charts.
    
*   Provide a user-friendly API for configuring and running simulations, including setting default countries.
    
*   Create comprehensive documentation, including tutorials and examples, to guide users in using the package effectively.
    
*   Goals Achieved By Mid-point Milestone: Completion of the core architecture, implementation of the `Microsimulation` and `IndividualSim` classes, and basic charting functionality.
    

Setup/Installation
------------------

The `policyengine` package will be hosted on GitHub and can be installed via pip:

```
pip install policyengine
```

Detailed installation instructions and dependencies will be provided in the package's README file.

Expected Outcome
----------------

The final product will be a well-documented and user-friendly Python package that enables users to perform policy simulations, conduct analyses, and generate visualizations across different countries. The package will provide a consistent interface for users to interact with our country-specific policy simulation packages, streamlining the process of cross-country comparisons and policy evaluation. Users will be able to reproduce a wide range of charts and visualizations from the PolicyEngine web interface programmatically, facilitating in-depth analysis and customization of visual representations.

Acceptance Criteria
-------------------

*   The `policyengine` package is available on GitHub and can be installed via pip.
    
*   The package provides the `Microsimulation` and `IndividualSim` classes for policy simulations.
    
*   Users can easily configure and run simulations, including setting default countries.
    
*   The package includes analytics and charting modules for cross-country analyses and visualizations.
    
*   Users can reproduce charts from the PolicyEngine web interface, including budgetary breakdowns, charts by income decile, poverty breakdowns by demographic groups, income inequality impacts for microsimulations, net income and marginal tax rates for individual households, and evolution of policy parameters' values.
    
*   Plotly is used for creating interactive and visually appealing charts.
    
*   Comprehensive documentation, including tutorials and examples, is available to guide users in using the package effectively.
    

Implementation Details
----------------------

*   The `policyengine` package will be developed in Python, leveraging existing country-specific packages (e.g., `policyengine_us`, `policyengine_uk`).
    
*   The package will follow a modular architecture, with separate modules for simulations, analytics, charting, and configuration.
    
*   The `Microsimulation` and `IndividualSim` classes will be implemented to provide a consistent interface for policy simulations across different countries.
    
*   The package will utilize Plotly for creating interactive and customizable charts and visualizations.
    
*   Chart reproduction functionality will be implemented to enable users to generate charts similar to those in the PolicyEngine web interface.
    
*   Continuous Integration and Continuous Deployment (CI/CD) practices will be followed to ensure code quality and automated testing.
    

Mockups/Wireframes
------------------

(Mockups and wireframes will be linked here when ready.)

Product Name
------------

PolicyEngine

Organisation Name
-----------------

PolicyEngine

Domain
------

*   Policy Simulation
    
*   Economic Modeling
    
*   Data Analysis
    
*   Data Visualization
    

Tech Skills Needed
------------------

*   Python
    
*   Data Analysis (pandas)
    
*   Data Visualization (Plotly)
    
*   Package Development
    
*   Documentation
    
*   Testing
    
*   CI/CD
    

Mentor(s)
---------

@nikhilwoodruff, co-founder and CTO @anth-volk, software engineer and developer community manager

Category
--------

*   Data Science
    
*   Economic Modeling
    
*   Package Development
    
*   Documentation
    
*   Testing
    
*   Data Visualization
    

Related Issues
--------------

*   Development of R and Stata wrappers for the `policyengine` package.
*   Exploration of compiling the package to WebAssembly for improved performance in web-based applications.

**Comment by masterismail** [comment]
Hey @MaxGhenis! I'm super interested in this project! I've been building APIs and AI models for a while now, and this sounds like a great fit. 

Is there a recommended way to chat with the mentors? I'd love to discuss how I can jump in and help out with this policyengine package.

Thanks!

**Comment by MadhukeshSingh** [comment]
Hi there, @MaxGhenis  , I'm passionate about machine learning, building APIs, and I'm eager to join this project.

Here's a bit about myself:
I am Madhukesh Singh, currently studying at the National Institute of Technology, Hamirpur, in my third year.

My experience includes working on image processing, computer vision, and object detection in satellite imagery during my internship as an AI developer at DRDO DYSL.AI.

Is there a preferred method for communicating with the mentors? how I can contribute.

**Comment by Sayanjones** [comment]
Hey @MaxGhenis I'm interested in contributing to the policyengine Python package! My skills in Python (pandas, Plotly), package development, and testing align well with your project.

I'm eager to help with chart reproduction functionality, data analysis/charting modules, or other general development tasks.

I've reviewed your goals and feel I can make valuable contributions. Please let me know how to get started!

**Comment by KDwevedi** [comment]
comment

**Comment by rajat-malvi** [comment]
Hello @MaxGhenis, I'm a beginner in the field currently exploring data analysis. I am a student who recently created a news scraping website. I used Python's regular expression module to clean the data before storing it in a PostgreSQL database. I'm eager to delve deeper into data analysis.

**Comment by AbhimanyuSamagra** [comment]
Do not ask process related questions about how to apply and who to contact in the above ticket. The only questions allowed are about technical aspects of the project itself. If you want help with the process, you can refer instructions listed on [Unstop](https://unstop.com/competitions/dedicated-mentoring-program-dmp-2024-code-for-govtech-932803?lb=7gWXVfKv) and any further queries can be taken up on our [Discord channel](https://discord.com/invite/VPrXf7Jxpr) titled DMP queries. Here's a [Video Tutorial](https://youtu.be/nMW-nD8WzHY) on how to submit a proposal for a project.

**Comment by Tushar3021** [comment]
I came across your Government Policy Simulation project and I'm interested in contributing. I have experience in Python, data analysis, and visualization.

**Comment by Sarcastic-Ajeet** [comment]
Hello @nikhilwoodruff @MaxGhenis,
I'm beginner for these type of project. Please let me know I could contribute. I have good knowledge of python, data analysis,
data visualization.

**Comment by MaxGhenis** [comment]
@Tushar3021 and @Sarcastic-Ajeet please see https://github.com/PolicyEngine/policyengine.py/issues/1#issuecomment-2072008367

**Comment by nsadana60** [comment]
Hello @nikhilwoodruff @MaxGhenis,
I'm sadana .i'm eager to contribute to this project(Government Policy Simulation project ) and to learn new skills .

**Comment by MaxGhenis** [comment]
Do not comment to express interest

**Comment by anth-volk** [comment]
<img width="932" alt="Screen Shot 2024-05-08 at 5 55 14 PM" src="https://github.com/PolicyEngine/policyengine.py/assets/14987227/20f54cb1-c253-4fc0-abca-5548b9368c75">

**Comment by KURAPATIHARIKA** [comment]
Helloo @MaxGhenis ,I'm a beginner for this kind of projects . I'm a student who is good at python, data analysis ...even completed my internship related to data science in sparks foundation...i'm eager to contribute my skills at this project and ready to explore new things...

**Comment by nikhilwoodruff** [comment]
# Weekly goals w/c 24th June

- [x] Add basic Pytest test Inequality metrics asserting that we match the PolicyEngine numbers (passing)
- [x] Add logic and tests (same as above) for all 6 poverty metrics

# Weekly goals w/c 2nd July

- [x] Finish six poverty metrics
- [x] Add budgetary impact metrics
- [x] Tests for those

# Weekly goals w/c 8th July

- [x] Finish vast majority of outstanding metrics
- [x] Add tests for any metrics added

# Weekly goals w/c 15th July

- [x] Finish remaining metrics in https://github.com/PolicyEngine/policyengine.py/issues/11
- [x] Add tests and documentation for all remaining metrics

**Comment by masterismail** [comment]
# Weekly Learnings / 24th June
This week, I learned about Pytest and GitHub workflows, as well as GitHub Actions.

**Comment by nikhilwoodruff** [comment]
Closing since the program is now ended.
