### ISSUE TITLE
Make a comprehensive list of all the impact types

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine.py#11]
We have inequality (great!) but there are probably 30 in total, including decile breakdowns.

**Comment by masterismail** [comment]
1. Budgetary impact
   - [ ] Overall
   - [ ] By program
2. Distributional impact
   - [ ] By income decile
     - [ ] Relative
     - [ ] Average
   - [ ] By wealth decile
     - [ ] Relative
     - [ ] Average
3. Winners and losers
   - [ ] By income decile
   - [ ] By wealth decile
4. Poverty impact
   - [ ] Regular poverty
     - [ ] By age
     - [ ] By gender
   - [ ] Deep poverty
     - [ ] By age
     - [ ] By gender
5. - [ ] Inequality impact   
6. Labour supply impact
   - [ ] Earnings
     - [ ] Overall
       - [ ] Relative
       - [ ] Absolute
     - [ ] By decile
       - [ ] Relative
         - [ ] Total
         - [ ] Income effect
         - [ ] Substitution effect
       - [ ] Absolute
         - [ ] Total
         - [ ] Income effect
         - [ ] Substitution effect
